In [2]:
import numpy as np

mat = np.array([[1, 2], [3, 4]])
c = np.array([[6 , 7], [8, 9]])

ad = np.array([[0, 0], [0, 0]])

for i in range(2):
    for j in range(2):
        ad[i][j] = mat[i][j] + c[i][j]
print(ad)

[[ 7  9]
 [11 13]]


In [3]:
sub = np.array([[0, 0], [0, 0]])
for i in range(2):
    for j in range(2):
        sub[i][j] = mat[i][j] - c[i][j]
print(sub)

[[-5 -5]
 [-5 -5]]


In [4]:
mult = np.array([[0, 0], [0, 0]])

for i in range(2):
    for j in range(2):
        for k in range(2):
            mult[i][j] += mat[i][k] * c[k][j]
print(mult)

[[22 25]
 [50 57]]


In [24]:
def mat_mult(a: list, b: list):
    if len(a[0]) == len(b):
        mul = np.array([[0 for i in range(len(b[0]))] for j in range(len(a))])
    
        for i in range(len(a)):
            for j in range(len(b[0])):
                for k in range(len(a[0])):
                    mul[i][j] += a[i][k] * b[k][j]
        
        print(mul)
    else:
        print('Multiplication not possible')

In [13]:
new = np.array([[7, 8],[4, 6], [2, 9]])

In [25]:
mat_mult(mat, c)
mat_mult(mat, new)
mat_mult(new, c)

[[22 25]
 [50 57]]
Multiplication not possible
[[106 121]
 [ 72  82]
 [ 84  95]]
