In [3]:
import numpy as np

# 1. Appending a single value to a 1D array
arr1 = np.array([1, 2, 3])
new_arr1 = np.append(arr1, 4)
print(f"Original array (1D): {arr1}")
print(f"New array after appending single value: {new_arr1}")

# 2. Appending a 1D array to another 1D array
arr2 = np.array([5, 6, 7])
new_arr2 = np.append(arr1, arr2)
print(f"New array after appending 1D array: {new_arr2}")

# 3. Appending to a 2D array along a specific axis
arr_2d = np.array([[1, 2], [3, 4]])
values_to_append_row = np.array([[5, 6]]) # Must match column count for axis=0
values_to_append_col = np.array([[7], [8]]) # Must match row count for axis=1
print('-', values_to_append_row)
print('-',values_to_append_col)

# Appending a row (axis=0)
new_arr_2d_row = np.append(arr_2d, values_to_append_row, axis=0)
print(f"Original 2D array:\n{arr_2d}")
print(f"New 2D array after appending row (axis=0):\n{new_arr_2d_row}")

# Appending a column (axis=1)
new_arr_2d_col = np.append(arr_2d, values_to_append_col, axis=1)
print(f"New 2D array after appending column (axis=1):\n{new_arr_2d_col}")

# 4. Appending without specifying an axis (flattens arrays)
arr_flat = np.append(arr_2d, arr1)
print(f"New array after appending without axis (flattened): {arr_flat}")

Original array (1D): [1 2 3]
New array after appending single value: [1 2 3 4]
New array after appending 1D array: [1 2 3 5 6 7]
- [[5 6]]
- [[7]
 [8]]
Original 2D array:
[[1 2]
 [3 4]]
New 2D array after appending row (axis=0):
[[1 2]
 [3 4]
 [5 6]]
New 2D array after appending column (axis=1):
[[1 2 7]
 [3 4 8]]
New array after appending without axis (flattened): [1 2 3 4 1 2 3]
