In [14]:
import numpy as np

dt = np.array([[2, 1], [4, 3], [5, 4]])

nr = len(dt)
nc = len(dt[0])

mean = [sum(dt[i][j] for i in range(nr)) / nr for j in range(nc)]

cnt = dt - mean

print(cnt)

[[-1.66666667 -1.66666667]
 [ 0.33333333  0.33333333]
 [ 1.33333333  1.33333333]]


In [15]:
cov = np.array([[0] * nc for i in range(nc)], dtype = float)

for i in range(nc):
    for j in range(nc):
        for k in range(nr):
            cov[i][j] += cnt[k][i] *cnt[k][j] / (nr - 1)
            cov[i][j] = round(cov[i][j], 2)

print(cov)

[[2.34 2.34]
 [2.34 2.34]]


In [18]:
a, b, c, d = cov[0, 0], cov[0, 1], cov[1, 0], cov[1, 1]

coef = [1, -(a + d), a * d - b * c]
l = np.roots(coef)
L = max(l)

I = np.array([[1, 0], [0, 1]])

cov_L = cov - (L * I)

Evr = [1, 0]
Evr[1] = -(cov_L[0, 0] / cov_L[0, 1])

print(Evr)

[1, 1.0]


In [19]:
pjt = [0] * nr

for i in range(nr):
    for j in range(nc):
        pjt[i] += cnt[i][j] * Evr[j]

print(pjt)

[-3.333333333333333, 0.666666666666667, 2.666666666666667]


In [23]:
s = np.array([[0] * nc] * nr)
print(s)

[[0 0]
 [0 0]
 [0 0]]
