In [1]:
import numpy as np

# Vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print("a + b =", a + b)

# Scalar multiplication
print("3 * a =", 3 * a)

# Subtraction
print("b - a =", b - a)


a + b = [5 7 9]
3 * a = [3 6 9]
b - a = [3 3 3]


In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("A + B:\n", A + B)

# Matrix multiplication
print("A * B (element-wise):\n", A * B)
print("A @ B (matrix product):\n", A @ B)

# Transpose
print("Transpose of A:\n", A.T)


A + B:
 [[ 6  8]
 [10 12]]
A * B (element-wise):
 [[ 5 12]
 [21 32]]
A @ B (matrix product):
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [3]:
import numpy as np

# Define A
A = np.array([[2, 3], [1, 1]])
b = np.array([8, 3])

# Inverse of A
A_inv = np.linalg.inv(A)

# Solve for x: x = A^-1 * b
x = A_inv @ b
print("Solution vector x =", x)

# Determinant
det = np.linalg.det(A)
print("Determinant of A =", det)


Solution vector x = [1. 2.]
Determinant of A = -1.0


In [4]:
import numpy as np

A = np.array([
    [-2, 2, -3],
    [2, 1, -6],
    [-1, -2, 0]
])

eigvals, eigvecs = np.linalg.eig(A)

print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Eigenvalues: [-3.  5. -3.]
Eigenvectors:
 [[-0.95257934  0.40824829  0.06498304]
 [ 0.27216553  0.81649658  0.82015882]
 [-0.13608276 -0.40824829  0.56843356]]


In [10]:
import numpy as np

A = np.array([
    [4, 2],
    [1, 3]
])
I = np.array([
    [1, 0],
    [0, 1]
])

a, b = A[0, 0], A[0, 1]
c, d = A[1, 0], A[1, 1]

coeffs = [1, -(a + d), a * d - b * c]

eigenvalues = np.roots(coeffs)
print('Eigenvalues:', eigenvalues)

Eigenvalues: [5. 2.]


In [13]:
for i in eigenvalues:
    L = A - i * I
    x = 1
    if L[0, 1] != 0:
        y = -L[0, 0] / L[0, 1]
    elif L[1, 0] != 0:
        y = -L[1, 0] / L[1, 1]
    else:
        y = 0
    vector = [x, y]
    print('Eigenvector for', i, ':', vector)

Eigenvector for 5.0 : [1, 0.5]
Eigenvector for 2.0 : [1, -1.0]


In [20]:
l1 = ((a + d) + cmath.sqrt((a + d) ** 2 - 4 * (a * d - b * c))) / 2
l2 = ((a + d) - cmath.sqrt((a + d) ** 2 - 4 * (a * d - b * c))) / 2
print(l1, l2)

(5+0j) (2+0j)


In [26]:
import numpy as np
import cmath

A = np.array([
    [4, 2],
    [1, 3]
])
a, b = A[0, 0], A[0, 1]
c, d = A[1, 0], A[1, 1]
coeffs = [1, -(a + d), (a * d - b * c)]

l1 = ((a + d) + cmath.sqrt((a + d) ** 2 - 4 * (a * d - b * c))) / 2
l2 = ((a + d) - cmath.sqrt((a + d) ** 2 - 4 * (a * d - b * c))) / 2
Evu = [l1.real, l2.real]

print('Eigenvalues are', Evu)

I = np.array([
    [1, 0],
    [0, 1]
])

for i in Evu:
    L = A - i * I
    x = 1
    if L[0, 1] != 0:
        y = -L[0, 0] / L[0, 1]
    elif L[1, 0] != 0:
        y = -L[1, 0] / L[1, 1]
    else:
        y = 0
    vector = [x, y]
    print('Eigenvector for', i, ':', vector)

Eigenvalues are [5.0, 2.0]
Eigenvector for 5.0 : [1, 0.5]
Eigenvector for 2.0 : [1, -1.0]
