In [8]:
import numpy as np

# Step 0: Data
X = np.array([
    [2, 3],
    [3, 4],
    [4, 5],
    [5, 6]
])

# Step 1: Mean centering
mean = np.mean(X, axis=0)
print('mean', mean)
X_centered = X - mean
print('X_centered', X_centered)

# Step 2: Covariance matrix
cov_matrix = np.dot(X_centered.T, X_centered) / (X.shape[0] - 1)
print('cov_matrix', cov_matrix)

# Step 3: Eigenvalues & eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print('eigenvalues, eigenvectors', eigenvalues, eigenvectors)

# Step 4: Sort eigenvectors by eigenvalues
idx = np.argsort(eigenvalues)[::-1]
eigenvectors = eigenvectors[:, idx]

# Step 5: Select top component
W = eigenvectors[:, 0:1]

# Step 6: Project data
X_pca = np.dot(X_centered, W)

print(X_pca)


mean [3.5 4.5]
X_centered [[-1.5 -1.5]
 [-0.5 -0.5]
 [ 0.5  0.5]
 [ 1.5  1.5]]
cov_matrix [[1.66666667 1.66666667]
 [1.66666667 1.66666667]]
eigenvalues, eigenvectors [ 3.33333333e+00 -4.44089210e-16] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[-2.12132034]
 [-0.70710678]
 [ 0.70710678]
 [ 2.12132034]]


In [6]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
X_pca = pca.fit_transform(X)

print(X)
print(X_pca)

[[2 3]
 [3 4]
 [4 5]
 [5 6]]
[[-2.12132034]
 [-0.70710678]
 [ 0.70710678]
 [ 2.12132034]]


In [3]:
# Loss function: J(x) = x^2

x = 10          # initial guess
lr = 0.1        # learning rate
iterations = 10

for i in range(iterations):
    gradient = 2 * x      # derivative of x^2
    x = x - lr * gradient
    print(f"Iteration {i+1}: x = {x}")


Iteration 1: x = 8.0
Iteration 2: x = 6.4
Iteration 3: x = 5.12
Iteration 4: x = 4.096
Iteration 5: x = 3.2768
Iteration 6: x = 2.62144
Iteration 7: x = 2.0971520000000003
Iteration 8: x = 1.6777216000000004
Iteration 9: x = 1.3421772800000003
Iteration 10: x = 1.0737418240000003
