In [7]:
import numpy as np

arr = np.random.randint(0, 100, (10, 10))
print(arr)

[[93 94 91 48 35 47 29 33  4 77]
 [39  9 21 93 34 86 56 69 78 45]
 [86 47 79 83 10 86 54 71 75 92]
 [77 64 15 97 61  3 40 17 43 70]
 [42 10 67 40 94 25 74 51 67  3]
 [76 80 37  8 27  0 11 23 49  2]
 [75 53 98 96 21 64 44 54 38 67]
 [87 90 63 95 49 53 67 46 50 58]
 [52 96 41 88 44 97 78  4 90 40]
 [16 13 77 74 35 56 58 39  6  1]]


In [9]:
ar = np.array(arr)

In [11]:
max_val = np.max(ar)

In [12]:
max_val

98

In [16]:
ar = ar[1:, 1:]

In [18]:
import pandas as pd

In [20]:
df = pd.read_csv('/home/nihal_farooq_m/Bro_Files/Week 15/Datasets/EDA.csv')

In [22]:
df.head()

,Age,Salary,Experience_Years,Department,Gender,Performance_Score,Satisfaction_Level
0,56,43141.0,17.0,HR,Male,2.06,0.58
1,46,105356.0,13.0,Operations,Male,2.44,0.48
2,32,96910.0,17.0,HR,Male,2.04,0.72
3,60,81044.0,1.0,Operations,Female,2.81,0.58
4,25,92214.0,21.0,IT,Female,1.13,0.67


In [28]:
max_sal = df[df['Salary'] == max(df.Salary)]['Salary']
min_sal = df[df['Salary'] == min(df.Salary)]['Salary']
print('max', max_sal,'\nmin', min_sal)

max 39    119856.0
Name: Salary, dtype: float64 
min 63    25854.0
Name: Salary, dtype: float64


In [29]:
type(max_sal)

pandas.core.series.Series