In [13]:
import numpy as np
ra = np.random.randint(1, 100, size = (10, 10))
print(ra)
ra2 = np.random.randint(1, 100, size = (10, 10))
print(ra2)

[[34 11 27  5 74 15 93 86 81 82]
 [39 34 78 68  6 98 20 84 46 84]
 [93 53 38 38 40 57 68 84  6 25]
 [10 62 64  2 13 46 52 69  6 16]
 [67 77 68 83 85 37 87 56 16 39]
 [82 47 60  1 35 99 90 39  5 39]
 [48  6 71  3 94 69 89 40 85 21]
 [92 48  5 63 61 26 95 94 24 87]
 [92 15 17 12 15 59 66 93  5 79]
 [80 31 66 82 11 53 46 77 25 18]]
[[72 77 77 10 72 30  1 18 61 39]
 [75  9 66 68 12  3 57 69 30 68]
 [55 49 92 91 27 73 64 97 91 41]
 [92 46 49  3 25 32 79  9 43 58]
 [94 43 33 10 92 52 68 71  7 49]
 [69 18 67  4 24 36 85 15 85 97]
 [47 67 92 26 86 72 55 62 87 74]
 [26 36 20 29 14 74 28 42 14 16]
 [ 1 79 14 19  7 75 89 46  5 23]
 [21  1 35 60 90 48 15 66 66  3]]


78

In [12]:
ra[5:6,5:6]

array([[98]])

In [16]:
de = np.delete(ra, 1,axis=1)
print(de)

[[34 27  5 74 15 93 86 81 82]
 [39 78 68  6 98 20 84 46 84]
 [93 38 38 40 57 68 84  6 25]
 [10 64  2 13 46 52 69  6 16]
 [67 68 83 85 37 87 56 16 39]
 [82 60  1 35 99 90 39  5 39]
 [48 71  3 94 69 89 40 85 21]
 [92  5 63 61 26 95 94 24 87]
 [92 17 12 15 59 66 93  5 79]
 [80 66 82 11 53 46 77 25 18]]


NameError: name 'ra2' is not defined

In [19]:
arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr
print(type(arr))

<class 'list'>


In [39]:
import array
ary = array.array('i',[1, 2, 3]
    # [4, 5, 6],
    # [7, 8, 9]
)
ary

array('i', [1, 2, 3])

In [37]:
import array
arr= array.array('i',[1,2,3])
arr
type(arr)

array.array