In [1]:
import pandas as pd
import scipy.stats as stats
import numpy as np

In [2]:
data = pd.read_csv('chi_dataset.csv')
data

,Gender,Preference
0,Female,Tea
1,Female,Coffee
2,Male,Coffee
3,Male,Coffee
4,Female,Coffee
5,Male,Coffee
6,Male,Coffee
7,Female,Tea
8,Male,Coffee
9,Male,Tea


In [3]:
table = pd.crosstab(data['Gender'], data['Preference'])
table

Preference,Coffee,Tea
Gender,,
Female,17,16
Male,17,10


In [4]:
obs = table.values
row_sum = obs.sum(axis = 1)
col_sum = obs.sum(axis = 0)
total = obs.sum()
obs

array([[17, 16],
       [17, 10]])

In [5]:
exp = np.outer(row_sum, col_sum) / total
exp


array([[18.7, 14.3],
       [15.3, 11.7]])

In [9]:
chi2 = ((obs - exp) ** 2 / exp).sum()
dof = (len(obs[0]) -1) * (len(obs) - 1)
print(chi2, dof)
chi,p,dof,exp1 = stats.chi2_contingency(table)
chi,dof,exp,exp1

0.7925407925407919 1


(0.39489921842862974,
 1,
 array([[18.7, 14.3],
        [15.3, 11.7]]),
 array([[18.7, 14.3],
        [15.3, 11.7]]))

In [13]:
p_v =  stats.chi2.sf(chi2, dof)
p_v,p

(0.6266670502614378, 0.529735340789638)