ai -> spam

20% spam

30% have ai

2% nonspam ai

In [ ]:
0.3*

In [1]:
import scipy.stats as stats

a = [20, 40, 43, 58, 28]
b = [38, 59, 40, 17, 50]
c = [74, 23, 76, 83, 12]

In [2]:
f_s, p_v = stats.f_oneway(a, b, c)

f_s, p_v

(0.6713704551233156, 0.5291967380006198)

In [15]:
import seaborn as sns

df = sns.load_dataset('iris')
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [16]:
df = df.dropna(subset = ['sepal_width'])

In [17]:
import pandas as pd

In [ ]:
set_ = pd.crosstab(df['species'], df['sepal_width'])
chi2, p_v, dof, ex = stats.chi2  (df)

In [18]:
set_ = pd.crosstab(df['species'], df['sepal_width'])
chi2, p_v, dof, ex = stats.chi2_contingency(set_)

chi2, p_v, dof, ex

(89.54628704628705,
 6.0160314822070716e-05,
 44,
 array([[0.33333333, 1.        , 1.33333333, 1.        , 2.66666667,
         1.66666667, 3.        , 4.66666667, 3.33333333, 8.66666667,
         3.66666667, 4.33333333, 2.        , 4.        , 2.        ,
         1.33333333, 1.        , 2.        , 0.66666667, 0.33333333,
         0.33333333, 0.33333333, 0.33333333],
        [0.33333333, 1.        , 1.33333333, 1.        , 2.66666667,
         1.66666667, 3.        , 4.66666667, 3.33333333, 8.66666667,
         3.66666667, 4.33333333, 2.        , 4.        , 2.        ,
         1.33333333, 1.        , 2.        , 0.66666667, 0.33333333,
         0.33333333, 0.33333333, 0.33333333],
        [0.33333333, 1.        , 1.33333333, 1.        , 2.66666667,
         1.66666667, 3.        , 4.66666667, 3.33333333, 8.66666667,
         3.66666667, 4.33333333, 2.        , 4.        , 2.        ,
         1.33333333, 1.        , 2.        , 0.66666667, 0.33333333,
         0.33333333, 0.3333333

In [2]:
import scipy.stats as stats
import pandas as pd
import seaborn as sns

iris = sns.load_dataset('iris')
iris

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [3]:
iris['sepal_length_cat'] = pd.cut(iris['sepal_length'], bins = 3, labels=['low', 'med', 'high'])
iris

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_length_cat
0,5.1,3.5,1.4,0.2,setosa,low
1,4.9,3.0,1.4,0.2,setosa,low
2,4.7,3.2,1.3,0.2,setosa,low
3,4.6,3.1,1.5,0.2,setosa,low
4,5.0,3.6,1.4,0.2,setosa,low
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,med
146,6.3,2.5,5.0,1.9,virginica,med
147,6.5,3.0,5.2,2.0,virginica,med
148,6.2,3.4,5.4,2.3,virginica,med


In [4]:
contingency = pd.crosstab(iris['sepal_length_cat'], iris['species'])
contingency

species,setosa,versicolor,virginica
sepal_length_cat,,,
low,47,11,1
med,3,36,32
high,0,3,17


In [6]:
chi2, p, dof, exp = stats.chi2_contingency(contingency)
print(chi2,'\n', p,'\n', dof,'\n', exp)

111.63387443303891 
 3.2620453090172096e-23 
 4 
 [[19.66666667 19.66666667 19.66666667]
 [23.66666667 23.66666667 23.66666667]
 [ 6.66666667  6.66666667  6.66666667]]


In [9]:
obs = contingency.values
row_sums = obs.sum(axis = 1)
col_sums = obs.sum(axis = 0)
total = obs.sum()
total

150

In [11]:
import numpy as np

expect = np.outer(row_sums, col_sums) / total
expect

array([[19.66666667, 19.66666667, 19.66666667],
       [23.66666667, 23.66666667, 23.66666667],
       [ 6.66666667,  6.66666667,  6.66666667]])

In [12]:
chi2_man = ((obs - expect) ** 2 / expect).sum()
dof_man = (len(row_sums) - 1) * (len(col_sums) - 1)
dof_man

4

In [22]:
chi2_man

111.63387443303891

In [18]:
p_v = 1 - stats.chi2.cdf(chi2_man, dof_man)
p_v

0.0

In [21]:
p_v_sf =stats.chi2.sf(chi2_man, dof_man)
p_v_sf

3.2620453090172096e-23