In [1]:
et = [6, 3, 8, 3, 9]

e = sorted(et, key = lambda x : x % 2 == 0)
e

[3, 3, 9, 6, 8]

In [2]:
# iterator
class CountUp:
    def __init__(self, n):
        self.n = n
        self.i = 1

    def __iter__(self):
        return self

    def __next__(self):
        if self.i > self.n:
            raise StopIteration
        val = self.i
        self.i += 1
        return val

for x in CountUp(5):
    print(x)


1
2
3
4
5


In [1]:
class MyIterator:
    def __init__(self, data):
        self.data = data
        self.index = 0  # state

    def __iter__(self):  
        return self

    def __next__(self):
        if self.index >= len(self.data):
            raise StopIteration
        value = self.data[self.index]
        self.index += 1
        return value

it = MyIterator([10,20,30])
for x in it:
    print(x)


10
20
30


In [3]:
# generator
def count_up(n):
    for i in range(1, n + 1):
        yield i

for x in count_up(5):
    print(x)


1
2
3
4
5


In [2]:
def countdown(n):
    while n > 0:
        yield n
        n -= 1

for x in countdown(5):
    print(x)
def announce(func):
    def wrapper():
        print("Before function runs")
        func()
        print("After function runs")
    return wrapper

@announce
def hello():
    print("Hello world!")

hello()


5
4
3
2
1


In [4]:
# decorator
def my_decorator(func):
    def wrapper():
        print("Before")
        func()
        print("After")
    return wrapper

@my_decorator
def say_hi():
    print("Hi")

say_hi()


Before
Hi
After


In [3]:
# original function → decorator adds features → final behavior

def announce(func):
    def wrapper():
        print("Before function runs")
        func()
        print("After function runs")
    return wrapper

@announce
def hello():
    print("Hello world!")

hello()


Before function runs
Hello world!
After function runs


In [8]:
# Practical ML use: timing
import time

def timer(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        print("Time:", time.time() - start)
        return result
    return wrapper

@timer
def say_hi():
    print("Hi")

say_hi()

Hi
Time: 0.0001857280731201172


In [9]:
# oops
# polymorphism
class Model:
    def train(self):
        pass

class LinearRegression(Model):
    def train(self):
        print("Training LR")

class DecisionTree(Model):
    def train(self):
        print("Training DT")

models = [LinearRegression(), DecisionTree()]

for m in models:
    m.train()


Training LR
Training DT


In [4]:
# new
# Encapsulation

class Person:
    def __init__(self, name):
        self.name = name  # public
        self._age = 0     # internal

    def set_age(self, age):
        self._age = age


In [6]:
# Inheritance

class Animal:
    def speak(self):
        print("I make a sound")

class Dog(Animal):
    def speak(self):
        print("Bark!")

Dog().speak()


Bark!


In [7]:
# Polymorphism

class Cat(Animal):
    def speak(self):
        print("Meow!")

for obj in [Dog(), Cat()]:
    obj.speak()  # different outputs


Bark!
Meow!


In [8]:
# Abstraction

class Database:
    def connect(self):
        pass
    def query(self):
        pass


In [10]:
import numpy as np

arr = np.array([1,2,3,4])

arr * 2   # vectorized


array([2, 4, 6, 8])

In [11]:
[x * 2 for x in arr]


[2, 4, 6, 8]

In [12]:
X = np.array([[1,2,3],
              [4,5,6]])

mean = X.mean(axis=0)

X - mean


array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

In [13]:
arr = np.array([10, 20, 30, 40])
arr[arr > 20]


array([30, 40])

In [9]:
# List comprihention

squares = [x*x for x in range(5)]
squares

[0, 1, 4, 9, 16]

In [10]:
# Dictionary comprihention

square_dict = {x: x*x for x in range(5)}
square_dict

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [11]:
add = lambda a,b: a + b
print(add(3,4))


7


In [13]:
# Broadcasting

import numpy as np

A = np.array([[1,2],[3,4]])
mean = A.mean(axis=0)
A - mean  # broadcasts subtraction


array([[-1., -1.],
       [ 1.,  1.]])