# Week 8 - Notebook 1: Vectors & Matrix Operations

Learn scalar/vector/matrix concepts with NumPy

## 🔹 Scalars, Vectors, and Matrices

Explain the difference between scalar, vector, and matrix in your own words.

In [6]:
import numpy as np

scalar = 5
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])

print("Vector:", vector)
print("Matrix:\n", matrix)

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]


## 🔹 Vector Operations

- Addition
- Scalar multiplication
- Dot product

In [7]:
v1 = np.array([2, 3])
v2 = np.array([1, 4])

print("Addition:", v1 + v2)
print("Scalar multiplication:", 3 * v1)
print("Dot product:", np.dot(v1, v2))

Addition: [3 7]
Scalar multiplication: [6 9]
Dot product: 14


## 🔹 Matrix Operations

- Addition, Multiplication, Transpose
- Shape checking

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A + B =\n", A + B)
print("A @ B =\n", A @ B)
print("Transpose of A:\n", A.T)

A + B =
 [[ 6  8]
 [10 12]]
A @ B =
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


## 🔹 ML Link: Data Representation

Each row = one data point  
Each column = one feature

Try converting 3 points with 2 features into a matrix:

In [9]:
data = np.array([
    [1.5, 2.3],
    [0.7, 1.8],
    [2.2, 3.1]
])
print("Data matrix:\n", data)

Data matrix:
 [[1.5 2.3]
 [0.7 1.8]
 [2.2 3.1]]
